spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: aprendiz.desarrollo@asmetsalud.com
    password: pauaeloqfphlidzb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  config:
    import: optional:configserver:http://localhost:9999
  application:
    name: nexus
